services:
  mongodb:
    container_name: mongodb-wichat_en2b
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
     - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-wichat_en2b
    image: ghcr.io/arquisoft/wichat_en2b/authservice:latest
    profiles: ["dev", "prod"]
    build:
      context: ./users/authservice
      args:
        JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-wichat_en2b
    image: ghcr.io/arquisoft/wichat_en2b/userservice:latest
    profiles: ["dev", "prod"]
    build:
      context: ./users/userservice
      args:
        JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    volumes:
      - userservice_images:/usr/src/userservice/public/images
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  llmservice:
    container_name: llmservice-wichat_en2b
    image: ghcr.io/arquisoft/wichat_en2b/llmservice:latest
    profiles: ["dev", "prod"]
    build:
      context: ./llmservice
      args:
        LLM_API_KEY: ${LLM_API_KEY}
    ports:
      - "8003:8003"
    networks:
      - mynetwork
  
  gameservice:
    container_name: gameservice-wichat_en2b
    image: ghcr.io/arquisoft/wichat_en2b/gameservice:latest
    profiles: ["dev", "prod"]
    build: ./gameservice
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    volumes:
      - gameservice_images:/usr/src/gameservice/public/images
    environment:
      MONGODB_URI: mongodb://mongodb:27017/game

  gatewayservice:
    container_name: gatewayservice-wichat_en2b
    image: ghcr.io/arquisoft/wichat_en2b/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - llmservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      LLM_SERVICE_URL: http://llmservice:8003
      GAME_SERVICE_URL: http://gameservice:8004

  webapp:
    container_name: webapp-wichat_en2b
    image: ghcr.io/arquisoft/wichat_en2b/webapp:latest
    profiles: ["dev", "prod"]
    build:
      context: ./webapp
      args:
        NEXT_PUBLIC_GATEWAY_SERVICE_URL: ${NEXT_PUBLIC_GATEWAY_SERVICE_URL}
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_en2b
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_en2b
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data:
  gameservice_images:
  userservice_images:

networks:
  mynetwork:
    driver: bridge