ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]

== Building Block View

=== Whitebox Overall System (C4 Level 1)

==== Overview Diagram

Business context diagram

[plantuml]
----
@startuml
set separator none
title Wichat EN2B - System Context

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<LLM>> {
  BackgroundColor #2d882d
  FontColor #ffffff
  BorderColor #1f5f1f
  shadowing false
}
skinparam person<<User>> {
  BackgroundColor #116611
  FontColor #ffffff
  BorderColor #0b470b
  shadowing false
}
skinparam rectangle<<WichatEN2B>> {
  BackgroundColor #2d882d
  FontColor #ffffff
  BorderColor #1f5f1f
  shadowing false
}
skinparam rectangle<<WikiData>> {
  BackgroundColor #2d882d
  FontColor #ffffff
  BorderColor #1f5f1f
  shadowing false
}

person "==User\n<size:10>[Person]</size>" <<User>> as User
rectangle "==WikiData\n<size:10>[Software System]</size>" <<WikiData>> as WikiData
rectangle "==LLM\n<size:10>[Software System]</size>" <<LLM>> as LLM
rectangle "==Wichat EN2B\n<size:10>[Software System]</size>" <<WichatEN2B>> as WichatEN2B

User .[#707070,thickness=2].> WichatEN2B : "<color:#707070>Uses"
WichatEN2B .[#707070,thickness=2].> WikiData : "<color:#707070>Gets information for questions"
WichatEN2B .[#707070,thickness=2].> LLM : "<color:#707070>Asks for hints"
@enduml
----

==== Motivation

The **Whitebox Overall System** diagram provides a high-level representation of the primary components and their interactions within the application, alongside the external systems it integrates with. This diagram is crucial for understanding the foundational architecture of the platform, showcasing the flow of data, system responsibilities, and external dependencies. It emphasizes the relationships between the various building blocks, such as the interaction between the user and the system, and how dynamic content is sourced via external APIs.

This diagram is pivotal in illustrating system interaction patterns, including user engagement with the platform and the external API interfaces used for content generation.

==== Contained Building Blocks

The key building blocks forming the overall system architecture include:

* **User**: Represents the end-user of the platform, who may authenticate in order to access the game functionality. Guest users can interact with the system and participate in gameplay. However, they will have limited access such as no multiplayer mode, saving the games...

* **Wichat EN2B Application**: The core application responsible for managing game mechanics, including the generation of questions and content. It encapsulates the application’s game logic and drives the user experience. Detailed breakdowns of its internal components are explored further in later sections.

* **WikiData API**: A third-party API providing structured knowledge, essential for the dynamic generation of trivia questions and content. The system queries the WikiData API for real-time data, which is used to populate game questions.

* **LLM API**: Another third-party API used for providing hints in response to user queries. It leverages large language models (such as GPT-based systems) to dynamically generate contextual content for enhancing user interactions. **Communication with the LLM occurs in a conversational manner**, where each request includes the entire conversation history (i.e., a list of all previous messages) to ensure context and continuity across interactions.

==== Important Interfaces

The **Important Interfaces** section defines the key interactions between system components and explains the methods through which the business requirements are met.

* **User to System Interaction**: Users engage with the system via a **web client** interface, which provides a rich UI experience with interactive elements such as forms, buttons, and dynamic feedback mechanisms. This client ensures a seamless user experience throughout the gameplay.

* **System to WikiData API Interaction**: The Wichat EN2B application interfaces with the **WikiData API** using a **Game service**. This service is in charge of the management of all the game related modules, such as the question generation and retrieval, the game state, the statistics, etc.

* **System to LLM API Interaction**: The Wichat EN2B application requests to the **LLM Service** the communication with the 
corresponding LLM, and this service is in charge of the propper connection witht the LLM.

* **Internal Services Communication**: Internal services within the Wichat EN2B application communicate over **RESTful APIs**. For example, the **Gateway Service** routes incoming requests to the appropriate internal services, while the **Game Service** ensures game state management and flow control.

=== Container Diagram (C4 Level 2)

==== Container Diagram

[plantuml]
----
@startuml
set separator none
title Wichat EN2B - Containers

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<WichatEN2B.DocumentationSystem>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<WichatEN2B.GameService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<WichatEN2B.GatewayService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<LLM>> {
  BackgroundColor #2d882d
  FontColor #ffffff
  BorderColor #1f5f1f
  shadowing false
}
skinparam rectangle<<WichatEN2B.LLMService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam database<<WichatEN2B.MongoDBDatabase>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam person<<User>> {
  BackgroundColor #116611
  FontColor #ffffff
  BorderColor #0b470b
  shadowing false
}
skinparam rectangle<<WichatEN2B.UserAuthenticationService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<WichatEN2B.UserGroupService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<WichatEN2B.Wihoot>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<WichatEN2B.UserCRUDService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<WichatEN2B.WebApplication>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}
skinparam rectangle<<WikiData>> {
  BackgroundColor #2d882d
  FontColor #ffffff
  BorderColor #1f5f1f
  shadowing false
}
skinparam rectangle<<WichatEN2B>> {
  BorderColor #1f5f1f
  FontColor #1f5f1f
  shadowing false
}

person "==User\n<size:10>[Person]</size>" <<User>> as User
rectangle "==WikiData\n<size:10>[Software System]</size>" <<WikiData>> as WikiData
rectangle "==LLM\n<size:10>[Software System]</size>" <<LLM>> as LLM

rectangle "Wichat EN2B\n<size:20>[Software System]</size>" <<WichatEN2B>> {
  rectangle "==Game Service\n<size:10>[Container]</size>" <<WichatEN2B.GameService>> as WichatEN2B.GameService
  database "==MongoDB Database\n<size:10>[Container]</size>" <<WichatEN2B.MongoDBDatabase>> as WichatEN2B.MongoDBDatabase
  rectangle "==Web Application\n<size:10>[Container]</size>" <<WichatEN2B.WebApplication>> as WichatEN2B.WebApplication
  rectangle "==Gateway Service\n<size:10>[Container]</size>" <<WichatEN2B.GatewayService>> as WichatEN2B.GatewayService
  rectangle "==Documentation System\n<size:10>[Container]</size>" <<WichatEN2B.DocumentationSystem>> as WichatEN2B.DocumentationSystem
  rectangle "==LLM Service\n<size:10>[Container]</size>" <<WichatEN2B.LLMService>> as WichatEN2B.LLMService
  rectangle "==User CRUD Service\n<size:10>[Container]</size>" <<WichatEN2B.UserCRUDService>> as WichatEN2B.UserCRUDService
  rectangle "==User Authentication Service\n<size:10>[Container]</size>" <<WichatEN2B.UserAuthenticationService>> as WichatEN2B.UserAuthenticationService
  rectangle "==User Group Service\n<size:10>[Container]</size>" <<WichatEN2B.UserGroupService>> as WichatEN2B.UserGroupService
  rectangle "==Wihoot Service\n<size:10>[Container]</size>" <<WichatEN2B.Wihoot>> as WichatEN2B.Wihoot
}

WichatEN2B.LLMService .[#707070,thickness=2].> LLM : "<color:#707070>LLM ask API call"
User .[#707070,thickness=2].> WichatEN2B.WebApplication : "<color:#707070>Uses"
WichatEN2B.WebApplication .[#707070,thickness=2].> WichatEN2B.GatewayService : "<color:#707070>Makes API calls"
WichatEN2B.GatewayService .[#707070,thickness=2].> WichatEN2B.LLMService : "<color:#707070>LLM ask API call"
WichatEN2B.GatewayService .[#707070,thickness=2].> WichatEN2B.GameService : "<color:#707070>Question API calls"
WichatEN2B.GatewayService .[#707070,thickness=2].> WichatEN2B.Wihoot : "<color:#707070>Wihoot API calls"
WichatEN2B.GameService .[#707070,thickness=2].> WikiData : "<color:#707070>Question batches API calls"
WichatEN2B.GameService .[#707070,thickness=2].> WichatEN2B.MongoDBDatabase : "<color:#707070>Stores game information"
WichatEN2B.Wihoot .[#707070,thickness=2].> WichatEN2B.MongoDBDatabase : "<color:#707070>Stores multiplayer information"
WichatEN2B.GatewayService .[#707070,thickness=2].> WichatEN2B.UserCRUDService : "<color:#707070>CRUD API calls"
WichatEN2B.GatewayService .[#707070,thickness=2].> WichatEN2B.UserAuthenticationService : "<color:#707070>Authentication API calls"
WichatEN2B.GatewayService .[#707070,thickness=2].> WichatEN2B.UserGroupService : "<color:#707070>Group management API calls"
WichatEN2B.UserCRUDService .[#707070,thickness=2].> WichatEN2B.MongoDBDatabase : "<color:#707070>User CRUD operations"
WichatEN2B.UserAuthenticationService .[#707070,thickness=2].> WichatEN2B.MongoDBDatabase : "<color:#707070>User authentication operations"
WichatEN2B.UserGroupService .[#707070,thickness=2].> WichatEN2B.MongoDBDatabase : "<color:#707070>Group operations"
@enduml

----

==== Motivation

The **Container Diagram** offers a more granular view of the Wichat EN2B application’s architecture, illustrating how the application is organized into discrete containers (services) and the relationships between them. This diagram is instrumental in detailing the internal structure of the system and clarifying how the platform's various components work together to deliver its functionality.

It serves as an essential tool for understanding how user interactions are processed, how game logic is managed, and how both external and internal data sources are leveraged for seamless gameplay.

==== Contained Building Blocks

The following containers represent the primary services within the Wichat EN2B application, each with distinct responsibilities:

* **Web Application**: The front-end interface between the user and the system. This container is responsible for rendering the user interface (UI) and handling user interactions. Developed using **NextJS** (a React framework), the Web Application ensures a responsive and dynamic experience. It communicates with internal services via API calls.

* **Gateway Service**: Serves as the entry point for external API requests. This container is responsible for routing incoming requests to the correct internal services, ensuring that requests are handled efficiently and securely.

* **Game Service**: This service manages the core game logic, including the flow of the game, the presentation of questions, tracking of user progress, and determining the game's end. It also handles the game state, such as the user's score and question set. It is 
responsible for generating and retrieving questions, together with retrieving the user statistics.

* **LLM Service**: This container interfaces with a **Large Language Model (LLM)** to provide hints, explanations, and additional content to assist the user during the game. It ensures that users receive context-sensitive content, enhancing the overall gaming experience by offering real-time dynamic information. Communication with the LLM API is conducted conversationally by passing the entire message history in each request to maintain context and coherence.

* **Wihoot Service**: This container manages the multiplayer game logic by letting users host or join a session to play the same quiz with other users. It was developped using **sockets**.

* **MongoDB Database**: The database responsible for storing persistent system data, including user profiles, game states, and scores. MongoDB is used for its flexibility in handling semi-structured data and its scalability.

* **User CRUD Service**: A container dedicated to managing user-specific API requests. It handles retrieval of user-related data, and management of user information such as creating, updating and deleting users.

* **User Authentication Service**: Handles the authentification part of the application. This service is in charge of logging a user in, registering a new one and validanting information.

* **User Group Service**: This container contains all the behaviour regarding groups such as group management (CRUD operations), joining and leaving a group.

==== Data Flow

Data flows between containers in a manner that ensures efficient communication and process execution. For example:

* When a user logs in via the Web Application, the system authenticates the request using the **User Service**. Guest users are also allowed to play the existing quizzes.
* After successful redirection, the user interacts with the **Game Service**.
* The **LLM Service** is called when the user requests a hint.

This modular design enhances scalability, maintainability, and fault isolation, ensuring that each component is specialized in its task while working seamlessly as part of the larger system.


=== Component Diagram (C4 Level 3)

==== Component Diagram

[plantuml]
----
@startuml
set separator none
title Wichat EN2B - Component Diagram (C4 Level 3)

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

' ======== Estilos personalizados =========
' Servicios principales
skinparam rectangle<<WichatEN2B.GameService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
}
skinparam rectangle<<WichatEN2B.GatewayService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
}
skinparam rectangle<<WichatEN2B.LLMService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
}
skinparam rectangle<<WichatEN2B.UserService>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
}

' Middleware (Azul)
skinparam rectangle<<Middleware>> {
  BackgroundColor #3366cc
  FontColor #ffffff
  BorderColor #1a3d7a
}

' Routers (Verde)
skinparam rectangle<<Router>> {
  BackgroundColor #33cc66
  FontColor #ffffff
  BorderColor #1a7a3d
}

' Modelos (Gris)
skinparam rectangle<<Model>> {
  BackgroundColor #cccccc
  FontColor #000000
  BorderColor #777777
}

' APIs externas
skinparam rectangle<<LLM>> {
  BackgroundColor #2d882d
  FontColor #ffffff
  BorderColor #1f5f1f
}
skinparam rectangle<<WikiData>> {
  BackgroundColor #2d882d
  FontColor #ffffff
  BorderColor #1f5f1f
}

' Database
skinparam database<<WichatEN2B.MongoDBDatabase>> {
  BackgroundColor #ff9933
  FontColor #ffffff
  BorderColor #b26b23
  shadowing false
}

' Main container
skinparam rectangle<<WichatEN2B>> {
  BorderColor #1f5f1f
  FontColor #1f5f1f
  shadowing false
}

rectangle "Wichat EN2B\n<size:10>[Software System]</size>" <<WichatEN2B>> {
  ' ======== Services =========
  rectangle "Gateway Service\n<size:10>[Service]</size>" <<WichatEN2B.GatewayService>> as GatewayServer
  rectangle "Game Service\n<size:10>[Service]</size>" <<WichatEN2B.GameService>> as GameServer
  rectangle "User Service\n<size:10>[Service]</size>" <<WichatEN2B.UserService>> as UserServer
  rectangle "LLM Service\n<size:10>[Service]</size>" <<WichatEN2B.LLMService>> as LLMServer
  rectangle "Auth Service\n<size:10>[Service]</size>" <<WichatEN2B.LLMService>> as AuthServer
  rectangle "Group Service\n<size:10>[Service]</size>" <<WichatEN2B.LLMService>> as GroupServer
  rectangle "Wihoot Service\n<size:10>[Service]</size>" <<WichatEN2B.LLMService>> as WihootServer

  ' ======== Routers =========
  rectangle "Quiz Router\n<size:10>[Router]</size>" <<Router>> as QuizRouter
  rectangle "Question Retriever Router\n<size:10>[Router]</size>" <<Router>> as QuestionRetrieverRouter
  rectangle "Game Info Router\n<size:10>[Router]</size>" <<Router>> as GameInfoRouter
  rectangle "Statistics Router\n<size:10>[Router]</size>" <<Router>> as StatisticsRouter
  rectangle "Auth Router\n<size:10>[Router]</size>" <<Router>> as AuthRouter
  rectangle "2fa Router\n<size:10>[Router]</size>" <<Router>> as 2faRouter
  rectangle "User CRUD Router\n<size:10>[Router]</size>" <<Router>> as UserCrudRouter
  rectangle "Group Router\n<size:10>[Router]</size>" <<Router>> as GroupRouter
  rectangle "Wihoot Router\n<size:10>[Router]</size>" <<Router>> as WihootRouter


  ' ======== Middleware =========
  rectangle "Auth Middleware\n<size:10>[Middleware]</size>" <<Middleware>> as AuthMiddleware

  ' ======== Models =========
  rectangle "Question Model\n<size:10>[Model]</size>" <<Model>> as QuestionModel
  rectangle "Game Result Model\n<size:10>[Model]</size>" <<Model>> as GameResultModel
  rectangle "User Model\n<size:10>[Model]</size>" <<Model>> as UserModel
  rectangle "Group Model\n<size:10>[Model]</size>" <<Model>> as GroupModel
  rectangle "Wihoot Model\n<size:10>[Model]</size>" <<Model>> as WihootModel

  ' ======== Database ========
  rectangle "MongoDB Database\n<size:10>[Container]</size>" <<WichatEN2B.MongoDBDatabase>> as MongoDBDatabase
}

' ======== APIs =========
rectangle "WikiData API\n<size:10>[External API]</size>" <<WikiData>> as WikiDataAPI
rectangle "LLM API\n<size:10>[External API]</size>" <<LLM>> as LLMAPI

' ======== Relations =========
GatewayServer -[#707070,thickness=2]-> GameServer : "Routes game API calls"
GatewayServer -[#707070,thickness=2]-> UserServer : "Routes user-related API calls"
GatewayServer -[#707070,thickness=2]-> LLMServer : "Routes LLM API calls"
GatewayServer -[#707070,thickness=2]-> AuthServer : "Routes authentication-related API calls"
GatewayServer -[#707070,thickness=2]-> GroupServer : "Routes group-related API calls"
GatewayServer -[#707070,thickness=2]-> WihootServer : "Routes multiplayer-related API calls"

AuthServer -[#707070,thickness=2]-> AuthRouter : "Routes user-related API calls"
AuthServer -[#707070,thickness=2]-> 2faRouter : "Routes 2fa-related API calls"
AuthRouter -[#707070,thickness=2]-> UserCrudRouter : "Requests user data"
2faRouter -[#707070,thickness=2]-> UserCrudRouter : "Handles authentication requests"

UserServer -[#707070,thickness=2]-> UserCrudRouter : "Routes user-related API calls"
UserCrudRouter -[#707070,thickness=2]-> UserModel : "Manages user data"
UserCrudRouter -[#707070,thickness=2]-> MongoDBDatabase : "Modifies users"

GroupServer -[#707070,thickness=2]-> GroupRouter : "Routes group-related API calls"
GroupRouter -[#707070,thickness=2]-> GroupModel : "Manages group data"
GroupRouter -[#707070,thickness=2]-> MongoDBDatabase : "Modifies groups"

WihootServer -[#707070,thickness=2]-> WihootRouter : "Routes multiplayer-related API calls"
WihootRouter -[#707070,thickness=2]-> WihootModel : "Manages multiplayer data"
WihootRouter -[#707070,thickness=2]-> MongoDBDatabase : "Saves multiplayer data"

LLMServer -[#707070,thickness=2]-> LLMAPI : "Processes language model requests"

AuthMiddleware -[#707070,thickness=2]-> GameInfoRouter : "Validates user authentication"
AuthMiddleware -[#707070,thickness=2]-> StatisticsRouter : "Validates user authentication"
AuthMiddleware -[#707070,thickness=2]-> GroupRouter : "Validates user authentication"

GameServer -[#707070,thickness=2]-> QuizRouter : "Fetches new questions"
GameServer -[#707070,thickness=2]-> QuestionRetrieverRouter : "Retrieves stored questions"
GameServer -[#707070,thickness=2]-> GameInfoRouter : "Handles game session data"
GameServer -[#707070,thickness=2]-> StatisticsRouter : "Processes game statistics"

QuizRouter -[#707070,thickness=2]-> QuestionModel : "Models the question schema"
QuizRouter -[#707070,thickness=2]-> WikiDataAPI : "Fetches trivia questions"
QuizRouter -[#707070,thickness=2]-> MongoDBDatabase : "Stores questions"

GameInfoRouter -[#707070,thickness=2]-> GameResultModel : "Models the question schema"
GameInfoRouter -[#707070,thickness=2]-> MongoDBDatabase : "Saves game information"

StatisticsRouter -[#707070,thickness=2]-> GameResultModel : "Models the question schema"
StatisticsRouter -[#707070,thickness=2]-> MongoDBDatabase : "Retrieves game information"

QuestionRetrieverRouter -[#707070,thickness=2]-> QuestionModel : "Models the question schema"
QuestionRetrieverRouter -[#707070,thickness=2]-> MongoDBDatabase : "Retrieves questions"

@enduml
----

==== Motivation

The **Component Diagram** (C4 Level 3) provides a detailed view of the internal structure of each service, focusing on the specific routers, logic components, and models. This level of detail is essential for developers working on individual services, as it clarifies the responsibilities of each component and their relationships.

==== Contained Building Blocks

* **Gateway Service**:
  - **Gateway Router**: Routes incoming HTTP requests to the appropriate internal services.
  - **Request Dispatcher**: Handles the logic for delegating requests to the correct service, ensuring communication between components.
  - **Monitoring**: Ensures the health and performance of the Gateway Service by tracking metrics such as request rates, response times, and error rates. This component provides insights into the system's operational status and helps identify potential issues.

* **Game Service**:
  - **Middleware**: Ensures only authenticated users can access to these points.
  - **Game Information Router**: Saves the game information and the game state.
  - **Quiz Router**: Is in charge of fetching questions from WikiData given the type and amount.
  - **Retriever Router**: Returns questions from our database given the requested parameters. It also validates the user's answers and sends the right answer to the LLM.
  - **Statistics Router**: Returns the current user game statistics for a given subject or for 
  the whole application. It also returns the leaderboard of the application, including the current user.

* **Auth Service**:
  - **Auth Service Router**: Manages authentication-related endpoints (login, register, validate). It uses the
  User CRUD router internally.

* **User Service**:
  - **User CRUD Router**: Handles user management endpoints (create, update, delete users).
  - **User Model**: Represents the user data structure and interacts with the database.

* **Group Service**:
  - **Group Router**: Handles the group management endpoints (CRUD, join, leave).
  - **Group Model**: Represents the group data sctructure and interacts with the database.
  - This service also uses the **middleware** to ensure only logged users can join or create groups.

* **LLM Service**:
  - **LLM Router**: Handles requests for hints.
  - **LLM Logic**: Communicates with the external LLM API to generate responses. 

* **Wihoot Service**:
  - **Wihoot Router**: Manages multiplayer games' endpoints.
  - **Wihoot Model**: The structure of the multiplayer data and interacts with the database.

* **External APIs**:
  - **WikiData API**: Provides structured data for generating questions.
  - **LLM API**: Offers dynamic content generation, such as hints and contextual information, based on user interactions.

==== External Communication

* **External API Integration**: The **WikiData API** is a critical external system that provides the data needed to generate game questions. The Wichat EN2B application sends HTTP requests to this API, utilizing SPARQL queries to retrieve relevant content based on predefined game rules.

* **LLM Communication**: The **LLM Service** facilitates interaction with external language models. It generates contextual hints, descriptions, and other textual content dynamically, based on the user’s queries or the state of the game, to guide users through the experience. Communication with the LLM is conversational, where the system passes the entire list of prior messages for each new request to maintain consistency and relevance in responses.

==== Data Flow

Each router contains one or several endpoints for its respective service. These router components interact with models or external APIs to fulfill the requests, ensuring a clear separation of concerns and maintainability.

For example:

- The **Gateway** routes a user request to the **Game Service** for game-related actions.

- The **Middleware** would check if the user is authenticated previously to any operation if required.

- The **Game Service** uses the **Game Retriever Router** and retrieves questions from the **Database** 

- The **LLM Service** communicates with the **LLM** throught the **LLM API** to generate hints or contextual responses for the user.

This modular design enhances scalability, maintainability, and fault isolation, ensuring that each component is specialized in its task while working seamlessly as part of the larger system.