ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View
This section focuses on describing the behaviour and interactions of the system's building blocks in form of scenarios.

=== User registration
Users must create an account if they do not have one. The behaviour of the application is:

[.text-center]
[plantuml,"Register diagram",png]
----
:User sends data;
:Verify credentials;

if (Credentials correct?) then (Yes)
    :Ask DB for existing user;
    :Return user;

    if (User exists?) then (Yes)
        :Show error to User;
        stop
    else (No)
        :Encrypt password and save;
        :Add user to the database;
        :Respond with new user;
        stop
    endif
else (No)
    :Show error to User;
    stop
endif

----

The errorless behaviour will be:

. The new user types the required information to create an account.

. Then, this information is verified (in the frontend in order not to overload the server with unnecessary requests). If the user manages to bypass this validation, the backend also verifies the data so that invalid data cannot reach the database.

. After that, the password is encrypted and a new user with the username, the encrypted password, its role and date of creation is made.

. This new user is then saved into the database.

. And sent back as the response.

=== User login


Users must have an account to use the application. The following sequence diagram shows how the application behaves when logging in.

[.text-center]
[plantuml,"Login diagram",png]
----
:User enters credentials;
:Verify credentials;

if (Credentials verified?) then (Yes)
    :Check user in Database;
    :Return user;

    if (Passwords match?) then (Yes)
        :Creates jsp token to Gateway;
        :User logs in;
        stop
    else (No)
        :Show error to User;
        stop
    endif
else (No)
    :Show error to User;
    stop
endif
----


This is the behaviour of the flawless execution of the login:

. The user types an username and a password. 

. After that, the credentials are checked and validated, and asks the database to find the user for the given username.

. The database returns the user.

. The Authentication Router verifies that the encrypted password given by the user and the encrypted password stored in the database match. If this happens, a JWT Token that expires in 1 hour is generated and sent.

. User logs in.


=== Game example

Here is the sequence diagram when playing the game.

[.text-center]
[plantuml,"Game diagram",png]
----
start

:User selects a game;
:Question are retrieved database;
:Show questions to User;

repeat :For each question;
    
    if (User asks for hint?) then (Yes)
        :Ask LLM for hint;
        :Show LLM answer to User;
    else (No)
        :User gives an answer;
        :Show correct answer to User;
    endif
repeat while (more questions?)

:Parse game to a valid format;
:Add game to MongoDB;

stop
----

. The user plays a game. 

. The application retrieves questions for that game from the database.

. Then, the questions are shown to the user one by one.

. When the game finishes, the app then saves all the information needed about the game to the desired format.

. The game is then saved in the database.

*In the case user asks for hints:*

. The player types a question for the LLM.

. The application collects the prompt and sends it to the LLM.

. The LLM makes the answer and returns it.

. The chat recieves it and shows the generated answer to the user.

=== Exceptions and Errors Scenarios

Possible errors regarding:

* Registering:
    - Invalid credentials (empty / blank).
    - Passwords do not match.
    - Username and passwords doo not meet the minimum numer of characters.
    - Using credentials from an already existing user: usernames must be different.
    - Database exception: connection lost, data loss.

* Login:
    - Empty or blank credentials.
    - Username does not exist.
    - Wrong password.
    - Database exception: connection lost, data loss.

* Game:
    - Wikidata error.
    - Database exception: connection lost, data loss.
    - LLM not answering to the user's prompt.
    - LLM hallucinations
    