global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 5s

# Rules for alerting and recording
rule_files:
  - "rules/alert_rules.yml"
  - "rules/recording_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: "gateway-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["gatewayservice:8000"]
        labels:
          service: "gateway"
          environment: "production"

  - job_name: "gateway-service-health"
    metrics_path: /health-metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["gatewayservice:8000"]
        labels:
          service: "gateway"
          check: "health"